In [1]:
import pandas
import pickle

# Import pandas df

In [2]:
data = pandas.read_pickle('raw_processed.pkl')
dataShort = data.iloc[0:10,19:46].copy()
data

,TIMESTAMP,LINE_NO,UTMX,UTMY,ELEVATION,CHANNEL_NO,RX_ALTITUDE,RX_ALTITUDE_STD,TX_ALTITUDE,TX_ALTITUDE_STD,...,DBDT_INUSE_Ch2GT31,DBDT_INUSE_Ch2GT32,DBDT_INUSE_Ch2GT33,DBDT_INUSE_Ch2GT34,DBDT_INUSE_Ch2GT35,DBDT_INUSE_Ch2GT36,DBDT_INUSE_Ch2GT37,closest_pos,closest_ind,VALID
0,43434.663700,100101,573558.0,4395767.7,63.11,1,49.11,0.060,50.55,0.060,...,9999,9999,9999,9999,9999,9999,9999,12.776932,11198.0,True
1,43434.663712,100101,573558.5,4395758.1,63.15,2,48.99,0.060,50.82,0.060,...,1,1,1,1,1,0,1,3.228002,11198.0,True
2,43434.663715,100101,573559.3,4395755.2,63.16,1,48.89,0.060,50.76,0.060,...,9999,9999,9999,9999,9999,9999,9999,0.223607,11198.0,True
3,43434.663727,100101,573564.0,4395745.9,63.16,2,47.32,0.062,49.20,0.062,...,1,1,1,1,1,0,1,0.141421,11200.0,True
4,43434.663731,100101,573566.0,4395743.1,63.15,1,46.60,0.063,48.41,0.063,...,9999,9999,9999,9999,9999,9999,9999,3.580503,11200.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7316,43436.748160,710101,579762.1,4390268.5,45.84,1,61.36,0.050,57.98,0.050,...,9999,9999,9999,9999,9999,9999,9999,344.506734,11709.0,False
7317,43436.748172,710101,579763.7,4390244.7,45.84,2,54.92,0.056,51.78,0.056,...,0,0,0,0,0,0,1,361.668536,11709.0,False
7318,43436.748176,710101,579764.3,4390237.4,45.84,1,53.01,0.058,50.01,0.058,...,9999,9999,9999,9999,9999,9999,9999,366.785932,11711.0,False
7319,43436.748188,710101,579766.2,4390212.7,45.84,2,47.11,0.065,44.69,0.065,...,0,0,0,0,0,0,1,384.290957,11711.0,False
7320,43436.748191,710101,579766.9,4390205.1,45.84,1,45.81,0.067,43.48,0.067,...,9999,9999,9999,9999,9999,9999,9999,389.763839,11711.0,False

In [10]:
data.shape

(48032, 216)